apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: motion-tenant-stack
  namespace: staging
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    ingress:
      hosts:
        - host: motion-web.staging.local
          paths:
            - path: /
              pathType: ImplementationSpecific
